<?php

namespace proGestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BoutiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoutiqueRepository extends EntityRepository
{
}
