<?php

namespace proGestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurRepository extends EntityRepository
{
  public function findAllOrderASC()
  {
    $qb = $this->createQueryBuilder('f');
  	$qb  -> select('f')
  	     -> orderBy('f.nom', 'ASC');

  	$array = $qb->getQuery()
  	     -> getResult();

  	return $array;
  }
}
