<?php

namespace proGestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrixMultipleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrixMultipleRepository extends EntityRepository
{
  public function findProduitQuantite($id, $quantite)
  {
    $qb = $this->_em->createQueryBuilder();

    $qb->select('p')
       ->from('proGestBundle:PrixMultiple', 'p')
       ->where('p.article = :id')
       ->setParameter('id', $id)
       ->andWhere('p.quantite = :quantite')
       ->setParameter('quantite', $quantite)
       ->orderBy('p.quantite', 'ASC');

    return $qb->getQuery()
              ->getResult();
  }

  public function findByArticle($id)
  {
    $qb = $this->createQueryBuilder('p');
  	$qb ->select('p.quantite, p.prix')
  	->where('p.article = :id')
  	->setParameter('id', $id)
    ->orderBy('p.quantite', 'ASC');

    $arrayAss= $qb->getQuery()
  	->getArrayResult();

  	// Transformer le tableau associatif en un tableau standard
  	$array = array();
  	foreach($arrayAss as $data)
  	{
  		$array[] = array("quantite"=>$data['quantite'], "prix"=>$data['prix']);
  	}

  	return $array;
  }
}
